debug

diff --git a/action.yaml b/action.yaml
--- a/action.yaml
+++ b/action.yaml
@@ -46,8 +46,10 @@ runs:
         fi
 
         if reviewdog --help 2>&1 | grep -- "-fail-level" >/dev/null; then
+          echo "-fail-level" >&2
           options="-fail-level=error"
         else
+          echo "-fail-on-error" >&2
           options="-fail-on-error=1"
         fi
 
