fix: use -fail-level if it's available (#784)
* fix: use -fail-level if it's available

* debug

* fix: fix the check of reviewdog option

diff --git a/action.yaml b/action.yaml
--- a/action.yaml
+++ b/action.yaml
@@ -44,6 +44,15 @@ runs:
         if [ "${{ github.event_name }}" = "pull_request" ]; then
           reporter=github-pr-review
         fi
+
+        if ( reviewdog --help 2>&1 || : ) | grep -- "-fail-level" >/dev/null; then
+          echo "use -fail-level" >&2
+          options="-fail-level=error"
+        else
+          echo "use -fail-on-error" >&2
+          options="-fail-on-error=1"
+        fi
+
         actionlint $ACTIONLINT_OPTIONS |
           reviewdog \
             -efm="%f:%l:%c: %m" \
@@ -51,4 +60,4 @@ runs:
             -filter-mode=nofilter \
             -reporter="$reporter" \
             -level=warning \
-            -fail-on-error=1
+            "$options"
